version: "3"
services:
    backend:
        build: ../backend/
        restart: always
        ports:
            - 9000:9000
        environment:
            PYTHONUNBUFFERED: 0
            MONGO_HOST: database
        links:
            - "database:database"
        depends_on:
            - database
        networks:
            - backend-network
            - admin-network
        volumes: 
            - ../data/images:/app/images
            
    database:
        image: mongo
        container_name: database
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ""
            MONGO_INITDB_ROOT_PASSWORD: ""
            MONGO_INITDB_DATABASE: "FastProjectKit"
        ports:
            - 27017:27017
        volumes: 
            - ../data/mongo:/data/db
        networks:
            - backend-network
    admin_frontend:
        build: ../admin_frontend/
        restart: always
        ports:
            - 8082:80
        networks:
            - backend-network
            - admin-network
    # frontend:
    #    build: 
    #    restart: 
    #    ports:
    #        - ""
    #    networks:
    #        - backend-network
    #        - frontend-network


networks:
    backend-network:
        driver: bridge
    admin-network:
        driver: bridge
    frontend-network:
       driver: bridge
        